<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8f5fa68c-5d2b-4d03-8488-fb0631585ac9</elementGuidId>
    <imagePath></imagePath>
    <name>link_personalDetails12</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/web/index.php/pim/viewPersonalDetails/empNumber/230') and equals(@text,'Personal Details')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text="Personal Details"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/web/index.php/pim/viewPersonalDetails/empNumber/230</value>
        <webElementGuid>34364dcb-b1a0-43c1-8df8-6a8093f947d9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Personal Details</value>
        <webElementGuid>34364dcb-b1a0-43c1-8df8-6a8093f947d9</webElementGuid>
    </webElementProperties>
</WebElementEntity>