<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>89c0048f-b6bc-4d5d-b6c9-b4ae81553efa</elementGuidId>
    <imagePath></imagePath>
    <name>link_contactDetails6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/web/index.php/pim/contactDetails/empNumber/224') and equals(@text,'Contact Details')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Contact Details"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/web/index.php/pim/contactDetails/empNumber/224</value>
        <webElementGuid>005d1180-5398-4284-891c-0ecc1be8b566</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Contact Details</value>
        <webElementGuid>005d1180-5398-4284-891c-0ecc1be8b566</webElementGuid>
    </webElementProperties>
</WebElementEntity>